AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a SNS Topic that is used to send Cerberus metrics and KPIs to, Cerberus operators can create Lambda's to process these messages if they desire to send them to places such as SingleFX

Resources:
  CerberusMetricsSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: Cerberus Metrics Topic
      TopicName: cerberus-metrics-topic

Outputs:
  CerberusMetricsTopicARN:
    Description: A topic for sending Cerberus metrics to.
    Value: !Ref CerberusMetricsSnsTopic
    Export:
      Name: CerberusMetricsTopicARN