language: java
jdk:
- oraclejdk8
script:
- "./gradlew clean cerberus-log-processor-lambda:shadowJar"
after_success:
- "./gradlew jacocoTestReport coveralls --stacktrace"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: e2OLsAjvpUtX5nJeQNib9y9kdtacdhJf/fqUz1Y+7sHQVngilXHYfPTFQqWcyu7HHGEFG1q/2F/XLrde9Qi9evb0dMoKHt0LFkyzAo74k26iDxTKCTPlUdh6BPHfa9fMAZvZ+YLOm/Be9xOq977dwrGHUCRh+xU5gIZ2y736zVRnObLpkUzR84aamIxCce2i7iZ0Jld1PwaT0X8pqbGHZQCVfxxYcKuhNN4nPD6TGtUye/W3/y9ilCwVxTL6p4AS09UXK5Z5otVd5mQbEL9JEsuJZ5fg42g7fscH1bLVCHGnHiQGBmaOyFrBnUSJ16NTrLyf4Y7qCFHCcecwkSZWlsSs6eZbc3yimYI36gkin/cjtVCOibWISdQOl4JohY6HLcHxcqvb1fjXQqsAuoi3gStrPSOjdIIPElb6E2vKRIRh+nyEjGwPsvQmrqO2dli3E15tNfGCYArqQI8utd3yo4jo8+CE/t1/GsBxMB/98pjvKwttqMXG0f9aEs/HQCKb5oW1KWd1wGgWnGS848IPq3xNOo43rcYIDgpBffJkZDku5ypcLBpUj9N6zcGhlABVvkqB7K8vBpHckPc/KUwjwZOXEnm0eYbXnI0ubdgMQ3UDzNUNrPFaLvCAa8NSOm8jB7ymXVoz1DzVth3tNNxlAP5a83UgI5EyvqCu5Gb1lMA=
  file_glob: true
  file: cerberus-log-processor-lambda/build/libs/cerberus-log-processor-lambda*
  on:
    repo: Nike-Inc/cerberus-serverless-components
    tags: true
