language: java
dist: trusty
jdk:
- oraclejdk8
script:
- "./gradlew clean cerberus-log-processor-lambda:shadowJar"
after_success:
- "./gradlew jacocoTestReport coveralls --stacktrace"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: e2OLsAjvpUtX5nJeQNib9y9kdtacdhJf/fqUz1Y+7sHQVngilXHYfPTFQqWcyu7HHGEFG1q/2F/XLrde9Qi9evb0dMoKHt0LFkyzAo74k26iDxTKCTPlUdh6BPHfa9fMAZvZ+YLOm/Be9xOq977dwrGHUCRh+xU5gIZ2y736zVRnObLpkUzR84aamIxCce2i7iZ0Jld1PwaT0X8pqbGHZQCVfxxYcKuhNN4nPD6TGtUye/W3/y9ilCwVxTL6p4AS09UXK5Z5otVd5mQbEL9JEsuJZ5fg42g7fscH1bLVCHGnHiQGBmaOyFrBnUSJ16NTrLyf4Y7qCFHCcecwkSZWlsSs6eZbc3yimYI36gkin/cjtVCOibWISdQOl4JohY6HLcHxcqvb1fjXQqsAuoi3gStrPSOjdIIPElb6E2vKRIRh+nyEjGwPsvQmrqO2dli3E15tNfGCYArqQI8utd3yo4jo8+CE/t1/GsBxMB/98pjvKwttqMXG0f9aEs/HQCKb5oW1KWd1wGgWnGS848IPq3xNOo43rcYIDgpBffJkZDku5ypcLBpUj9N6zcGhlABVvkqB7K8vBpHckPc/KUwjwZOXEnm0eYbXnI0ubdgMQ3UDzNUNrPFaLvCAa8NSOm8jB7ymXVoz1DzVth3tNNxlAP5a83UgI5EyvqCu5Gb1lMA=
  file_glob: true
  file: cerberus-log-processor-lambda/build/libs/cerberus-log-processor-lambda*
  on:
    repo: Nike-Inc/cerberus-serverless-components
    tags: true
notifications:
  slack:
    if: branch = master AND (type = push OR type=cron)
    on_success: change
    on_failure: always
    rooms:
      -  secure: jdeqaaz3LmlDPF16Ikd/0iGuIEr1kCWwzufkJncYsIY6E3wRy/7SJxMpnrTnXC8lpobl6nbrW8o2c1uFeZVz4sCt6UNwTUcHkVqNFmH6JDoyJL13YOsOdu1zLXjgnJhgWcIAHsZgE6HzdVwBADxLGLUuh9FZMox4GxtCX9QfKrITA2R64ZMfQ3VU2BZuKXLoQx30al/gcWJakDTpIlOg0GWTYDCL7G6BnZbybnoPeHRX1twXwYj/wmaU+DzJJ+nKOD5WkqecHwSCk2CQheEQNoosQi+rQTuMDYNrto0wi59LplCgT4/5KowBXz7EKBIw51P540/s7g/DbQHBc2Nej3snt0FnNGUn73PJ/simTlqVP7ngByB7f6Qq//e2oHv3RCXPg3UVEn3PYyAQ2bPAOfiu9HjdztI3mUJFFOlzfGRV7zd0lOz8NL7yj6MXjHOxQoYIWJhODmVhixDkJnrFwzzxBZJWVzlmx0C4BDeIS+nRKtdPjp9L3ojPQWhaRKp20BiRI9PMyXEou8mpfDV9gm+Tr2xdlY4x0WXTnKdo86igGqfgXKKOdk1JY8IOiyrv2BzRV5yPaFzTk2F/f8ehGCEUPFubTlGDU4p2K231j3XJj9d7vtiYq2/SZgv156kSFdCLZsANsME1b68BmUpL7iIpAH/dPwqk6naCDqvw81w=
