AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Authenticate with Cerberus using IAM Principal auth and clean up orphaned or inactive records
Parameters:
  CerberusUrl:
    Type: String
    Description: The Cerberus API to test.
  CerberusEnvironment:
    Type: String
    Description: The Cerberus environment.
  KmsExpirationPeriodInDays:
    Type: Number
    Description: Clean up KMS keys that have been inactive for n days.

Resources:

  # Cleanup Lambda function
  CerberusCleanUpFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: >-
         com.nike.cerberus.CerberusCleanUpHandler::runCleanUp
      Runtime: java8
      Description: Function to clean up for orphaned and inactive records in Cerberus
      MemorySize: 512
      Timeout: 300
      CodeUri: @@CODE_URI@@
      Role: !ImportValue CerberusAdminIamRoleARN
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 ? * MON-FRI *)
      Environment:
        Variables:
          IAM_PRINCIPAL_ARN: !ImportValue CerberusAdminIamRoleARN
          REGION: !Ref AWS::Region
          CERBERUS_URL: !Ref CerberusUrl
          ENVIRONMENT: !Ref CerberusEnvironment
          KMS_EXPIRATION_PERIOD_IN_DAYS: !Ref KmsExpirationPeriodInDays